// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEA0xEybdi1bIByu1W0aPq2nNWDEHsHFg',
    appId: '1:876667990340:web:0fd6e0a9a21edfef892711',
    messagingSenderId: '876667990340',
    projectId: 'crud-app-1a2eb',
    authDomain: 'crud-app-1a2eb.firebaseapp.com',
    storageBucket: 'crud-app-1a2eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUUo7axN8d7yxAn7mo1R0GWkQdnFYNLI',
    appId: '1:876667990340:android:18545dd703adc45a892711',
    messagingSenderId: '876667990340',
    projectId: 'crud-app-1a2eb',
    storageBucket: 'crud-app-1a2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBon7ajnkCBPgblhJrbKWXjRTluLIVt8Xo',
    appId: '1:876667990340:ios:750daf0849032b08892711',
    messagingSenderId: '876667990340',
    projectId: 'crud-app-1a2eb',
    storageBucket: 'crud-app-1a2eb.appspot.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBon7ajnkCBPgblhJrbKWXjRTluLIVt8Xo',
    appId: '1:876667990340:ios:fc0ef8e26a563404892711',
    messagingSenderId: '876667990340',
    projectId: 'crud-app-1a2eb',
    storageBucket: 'crud-app-1a2eb.appspot.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
